export const firebaseSeedData = {
  "actions_range": [
  {
    "id": "ATACAR",
    "data": {
      "action": "ATACAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Agressão física direta ou com feitiços ou armas, no calor do momento.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "Esta modalidade de combate foca em causar DANO.",
      "action_formula_lit": "INS + Proficiência com Feitiço ou Arma + Bônus +  1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Você se machuca, recebendo 2 de dano, e gastando 2 Energia.",
      "resultminus2": "Você se machuca, recebendo 1 de dano e gastando 1 Energia.",
      "resultminus1": "Você não consegue atingir o alvo, e perde 1 Energia.",
      "result0": "Você não consegue penetrar as defesas do adversário, mas uma versão fraca do Efeito do seu ataque ocorre, mas sem tirar dano.",
      "result1": "1x o dano do feitiço ou golpe no adversário.",
      "result2": "1x o dano no adversário, mais o Efeito do seu ataque.",
      "result3": "2x de dano no adversário mais Efeito.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "BLOQUEAR, CONTRA-ATACAR",
    "data": {
      "action": "BLOQUEAR, CONTRA-ATACAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Mitigar o ataque do adversário, com chance de devolver o DANO parcialmente ou integralmente. ",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "🛡",
      "action_type3": "⭯",
      "counter": [
        "DEF"
      ],
      "has_bonus": "Alerta, Ágil",
      "opp_has_bonus": "Focado",
      "action_condition": "Esta modalidade de combate foca em evitar DANO e ter a chance de refletir ou revidar.",
      "action_formula_lit": "INS + Proficiência com Feitiço ou Arma, Valor de DEF + Bônus +  1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Na sua tentativa de contratacar, você se expõe, e errando o contragolpe, acaba se machucando mais do que teria se só tivesse resistido ou se defendido.",
      "resultminus2": "Você perde o timing e acaba levando o golpe antes que possa se defender, e gasta 1 Energia.",
      "resultminus1": "Você consegue bloquear apenas metade do efeito,dano do golpe.",
      "result0": "Você bloqueia o dano, porém sem causar nada no adversário.",
      "result1": "Sua defesa dissipa 50% do dano e efeito do adversário, e gastando mais 1 Energia você manda de volta para ele os 50% restantes. Por 2 Energia, você pode escolher algum outro golpe para mandar no lugar, com chance de defesa do adversário.",
      "result2": "Bloqueia 100% do ataque e efeito do seu adversário.",
      "result3": "Com timing perfeito, neutraliza a investida do seu adversário e contrataca sem que ele possa se defender, refletindo o dano e o efeito originais imediatamente.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "INTERROMPER",
    "data": {
      "action": "INTERROMPER",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Realizar um ataque defensivo a impedir o proveniente do seu adversário.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "Alerta, Ágil",
      "opp_has_bonus": "Alerta, Ágil",
      "action_condition": "Precisa estar preparado, desconfiado, ou já engajado em combate. Com sucesso de +2 ou mais, seu golpe foi anterior ao do adversário que já atacou.",
      "action_formula_lit": "INS + Bônus +  1d3Fixo (sem adicionar Proficiência)",
      "action_formula_array": "-",
      "action_energy": "4⚡",
      "resultminus3": "Erra a execução do golpe, e produz algo inesperado, sofrendo um efeito negativo e perdendo a próxima vez",
      "resultminus2": "Sofre o efeito e perde a próxima vez",
      "resultminus1": "Perde a vez, errando o golpe ou feitiço",
      "result0": "Consegue executar o golpe ou feitiço e seu adversário sofrerá o efeito, mas você também receberá o golpe do inimigo, tendo errado o timing.",
      "result1": "Consegue atingir seu feitiço no adversário, porém depois dele já ter executado sua ação.",
      "result2": "Realiza o efeito desejado do feitiço ou golpe.",
      "result3": "1x Dano mais efeito. Você ganha mais uma vez, agindo rápida e decisivamente.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "RESISTIR IMPACTO",
    "data": {
      "action": "RESISTIR IMPACTO",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Tolerância à dor e resistência física. É a DEF quando nenhuma Ação de DEF pode ser realizada.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🛡",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "ATK"
      ],
      "has_bonus": "Tiver Armadura ou Escudo",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "PASS: POR + Armadura + Bônus + 1d3Fixo\r\nATV: POR + 1d(INS) + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Perde 4 pontos de vida e desmaia de dor.",
      "resultminus2": "Perde 3 pontos de vida e fica com -1d3 para qualquer ação seguinte.",
      "resultminus1": "Perde 2 pontos de vida e fica atordoado por um round inteiro.",
      "result0": "Perde 1 ponto de vida e fica levemente atordoado, perdendo sua vez, mas podendo agir após o seguinte à sua vez.",
      "result1": "Não perde nenhum ponto de vida, mas gasta 1 Energia e fica levemente Atordoado.",
      "result2": "Não perde nenhum ponto de vida.",
      "result3": "Não perde nenhum ponto de vida, e milagrosamente o impacto que recebe lhe dá mais forças ainda (+1d3) para contratacar.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "ARREMESSAR",
    "data": {
      "action": "ARREMESSAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Lançar objetos, projéteis e armas.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "Focado",
      "opp_has_bonus": "Alvo estiver em movimento",
      "action_condition": "A dificuldade do teste é de acordo com o Porte e distância do item.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": " 1⚡",
      "resultminus3": "Erra o alvo e acaba se machucando no processo, perdendo 2 PdV.",
      "resultminus2": "Erra o alvo e fica impossibilitado de tentar de novo.",
      "resultminus1": "Não consegue alcançar o alvo por 1 triz. Pode tentar de novo na próxima vez.",
      "result0": "Seu projétil chega no alvo, mas com pouca força, dando ao alvo +1d3 para se defender. Se a defesa do adversário for um contra-ataque, ver resultado da ação CONTRA-ATAQUE.",
      "result1": "Faz o item alcançar seu alvo, porém numa segunda tentativa e,ou usando o dobro da Energia.",
      "result2": "Lança o item na direção que deseja, fazendo-o alcançar seu alvo.",
      "result3": "Lança o objeto no alvo, a causa 2x o dano, ou tem uma surpresa positiva.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "CARREGAR, FORÇA",
    "data": {
      "action": "CARREGAR, FORÇA",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Levantar ou mover objetos pesados.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "-",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "Peso",
      "action_condition": "A dificuldade do teste é de acordo com o Porte do item.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Se machuca seriamente. Perde HP, fica com status de Sangrando perde 2 Energia.",
      "resultminus2": "Se machuca não muito seriamente. Perde um pouco de HP e 1 Energia.",
      "resultminus1": "Não consegue empurrar ou levantar o que está tentando. Ainda assim, gasta 1 Energia.",
      "result0": "Percebe que está prestes a conseguir, mas com algum estímulo, ajuda ou mecanismo externo pode conseguir a força que falta.",
      "result1": "Carrega com algum esforço, gastando 1 Energia.",
      "result2": "Carrega com pouco esforço.",
      "result3": "Carrega com facilidade.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "ESCALAR",
    "data": {
      "action": "ESCALAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Subir superfícies íngremes ou paredes.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "-",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "A dificuldade do teste é de acordo com o desafio do terreno ou obstáculo.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Sofre uma queda grave ou acidente, resultando em ferimentos graves.",
      "resultminus2": "Antes de conseguir alcançar a região necessária, sofre uma queda não muito séria e ferimentos leves.",
      "resultminus1": "Não consegue encontrar um ponto de apoio adequado, tornando a escalada impossível.",
      "result0": "A escalada é bem-sucedida, mas leva mais tempo do que o esperado.",
      "result1": "Enfrenta dificuldades, mas consegue recuperar o equilíbrio e continuar a escalada, ao gastar 2 Energia.",
      "result2": "O jogador completa a escalada com sucesso, atingindo o objetivo planejado gastando apenas 1 Energia.",
      "result3": "Você escala com maestria, sem gastar energia em excesso, e pode encontrar algo valioso no caminho.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "INICIATIVA, ALCANÇAR",
    "data": {
      "action": "INICIATIVA, ALCANÇAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Iniciativa: Determina a rapidez na tomada de ações em combate. Para disputar a ordem da vez de cada personagem na rodada, ou tentar interromper a sequência.\r\n\r\nAlcançar: Habilidade de correr até objetos ou criaturas distantes ou agarrar algo em movimento.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação, Ação Bônus",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "Iniciativa, Alcançar"
      ],
      "has_bonus": "Alerta",
      "opp_has_bonus": "Alerta",
      "action_condition": "A qualquer momento, gaste 2 Energia  para cortar a vez nos turnos. Com sucesso de +1 ou mais em Iniciativa, você corta a ação na frente do personagem da vez.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "4⚡*",
      "resultminus3": "Iniciativa: Se precipita e perde o timing, o fazendo cair, tropeçar assim se machucar e perder a próxima vez.\r\nAlcançar: Além de gastar muita energia (2) e fracassar em alcançar o alvo, você cai e se machuca, ou derruba e quebra algo importante.",
      "resultminus2": "Iniciativa:  Se precipita e perde o timing, perdendo a sua próxima vez.\r\nAlcançar:  Não consegue alcançar o alvo e gasta mais 1 Energia.",
      "resultminus1": "Iniciativa:  Seu adversário ganha a vez ou você não consegue interromper a sequência de ações.\r\nAlcançar:  Está bem próximo de alcançar o alvo, porém sem conseguir alcançá-lo.",
      "result0": "Iniciativa:  Consegue cortar a vez seguinte, não esta de agora.\r\nAlcançar:  Está pau a pau com o alvo, sem que nenhum dos dois consigam se tocar.",
      "result1": "Iniciativa:  Consegue cortar a vez e realizar sua nova ação, gastando 1 Energia.\r\nAlcançar:  Alcança o alvo por trás numa distância suficiente para engajar com ele.",
      "result2": "Iniciativa:  Consegue cortar a vez e realizar sua nova ação.\r\nAlcançar:  Ultrapassa o alvo, podendo engajar com ele pela frente.",
      "result3": "Iniciativa:  Consegue cortar a vez e terá +1d3 para realizar a próxima ação.\r\nAlcançar:  Ultrapassa o alvo, podendo engajar com ele pela frente, e faz o adversário gastar 2 energias.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "INTIMIDAR",
    "data": {
      "action": "INTIMIDAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Ameaçar ou assustar, fazendo alvo ceder (ser convencido) ou fugir.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Desafiar"
      ],
      "has_bonus": "Porte ou hierarquia superior",
      "opp_has_bonus": "Porte ou hierarquia superior",
      "action_condition": "-",
      "action_formula_lit": "Bônus em Persuasão ou ",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Alvo desmoraliza você, que acaba ficando intimidado no lugar dele, e deverá acatar o que ele quer. Ele fica hostil e ofendido.",
      "resultminus2": "Seu alvo não compra sua investida, e se torna hostil e pronto para atacar ou punir.",
      "resultminus1": "Seu alvo fica hesitante, mas finalmente decide não aceitar. Ele permanece na sua instância sem atacar nem recuar.",
      "result0": "Seu alvo está à beira de recuar, mas ainda precisa de alguma influência externa.",
      "result1": "Alvo fica parcialmente intimidado, e aceita fazer o que você quer se for algo razoável, embora contrariado e somente na sua frente.",
      "result2": "Alvo fica impressionado e amedrontado por você, e aceitará o que você propõe, mas afrontado.",
      "result3": "Alvo fica impressionado por você e lhe respeita, fazendo o que você deseja sem mais estar contrariado.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "DESAFIAR",
    "data": {
      "action": "DESAFIAR",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Resistência mental contra ameaças ou provocações.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Intimidar"
      ],
      "has_bonus": "Estresse",
      "opp_has_bonus": "seu personagem tiver Medo",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Seu personagem foge, ou é obrigado a acatar o que a Intimidação do inimigo demanda.",
      "resultminus2": "Seu personagem, além de ceder totalmente à Intimidação, fica se sentido desmoralizado e com medo. Status: Medo ou Estresse.",
      "resultminus1": "Seu personagem resiste mas fica intimidado pelo adversário; você deverá, na frente da pessoa pelo menos, fazer o que ela demanda, e só agir contrário a ela quando seu personagem não souber que ela está por perto. ",
      "result0": "A determinação do jogador impressiona o intimidador minimamente, fazendo com que reconsiderem sua abordagem.",
      "result1": "Você resiste à intimidação até certo ponto; faz o que lhe é demandado, mas também não é dissuadido de fazer o que você gostaria em seguida.",
      "result2": "Você resiste e não precisa acatar as demandas de quem lhe está intimidando.",
      "result3": "Seu personagem não teme a intimidação, e ganha +1d3 para sua próxima ação contra este inimigo.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "FORÇA DE VONTADE",
    "data": {
      "action": "FORÇA DE VONTADE",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Resistência mental e determinação em não mudar de ideia e persistir no que determinou.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "CONVENCIMENTO"
      ],
      "has_bonus": "Desconfiado",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Não somente falha como fica totalmente desmoralizado (Estresse ou Culpa) e acaba se machucando ou machucando alguém. ",
      "resultminus2": "Você não consegue resistir a investida do adversário, ou perde as esperanças, ficando preso num estado de Estresse ou Culpa até algo mudar na situação.",
      "resultminus1": "Se esforça bastante, mas no final acaba cedendo.",
      "result0": "Durante sua tentativa de prosseguir, acaba identificando alguma coisa fora do seu alcance para conseguir resistir. Terá a chance de comunicar a alguém para receber ajuda.",
      "result1": "Hesitando, você se mantêm firme na sua resolução. Mas tem que fazer alguam concessão ou gasta 1 Energia.",
      "result2": "Você se mantêm firme, recuperando sua Energia (1) na sua autoconfiança.",
      "result3": "Resiste qualquer investida mental. É capaz de continuar o que está fazendo apesar do medo, insegurança ou culpa. Inspira a todos os aliados presentes com +1d3 para a próxima ação pertinente ao uso da Força de Vontade.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "ORIENTAÇÃO, SOBREVIVÊNCIA",
    "data": {
      "action": "ORIENTAÇÃO, SOBREVIVÊNCIA",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Navegar e encontrar direções em um lugar novo ou confuso.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva, Ação",
      "img_action_type": "-",
      "action_type1": "💎",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Conhecer o Ambiente",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Está completamente perdido, já gastou 3 Energia e não conseguirá sair de onde está a menos que algo externo aconteça., Encontra algo danoso e é obrigado a chegar mais perto ou ingerir.",
      "resultminus2": "Está bastante perdido, e precisará gastar 2 Energia e vencer uma rolagem de Força de Vontade ou afim para não perder o controle., Encontra apenas algo potencialmente perigoso.",
      "resultminus1": "Está perdido, tem alguns elementos que dão alguma noção do caminho, mas teve que rodar muito para consegui-los. Gastou 2 Energias até agora, e se quiser sair deste lugar ou chegar até a interação com outro personagem, precisará gastar mais 2 Energias., Perde tempo e energia procurando mas não encontra nada últil.",
      "result0": "Receberá opções do Narrador, e deverá escolher entre elas. Sem saber qual é qual, uma é longa e tem obstáculos difíceis, outra é longa e sem muitos obstáculos, e uma é curta e com obstáculos médios.",
      "result1": "Identifica alguns elementos que podem guiá-lo, mas ainda não é capaz de ver um caminho claro e prático. Gastando 1 Energia ele poderá chegar até a entreada por onde veio ou encontrar com algum outro personagem, amigo ou inimigo., Gastando 1 Energia poderá encontrar algo útil, mas não ideal.",
      "result2": "Começa a se encontrar. Gastando 1 Energia ele consegue chegar ao próximo passo da jornada., Gastando 1 Energia consegue encontrar algo útil e apropriado pro que você precisa.",
      "result3": "Se encontra com facilidade. Sabe por onde veio e para onde deve ir., Encontra algo útil em quantidade suficiente para o que precisa.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "CLARIVIDÊNCIA",
    "data": {
      "action": "CLARIVIDÊNCIA",
      "att": "INS",
      "att_img": "🔥",
      "action_description": "Receba ua pista ou mensagem críptica da narração. A dificuldade dependerá do quão misteriosa ou precisa for a mensagem.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "Utilizar técnicas divinatórias como Cristalomancia, Astrologia, Quiromancia, etc., podem dar bônus.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Seu personagem se frustra de não conseguir divinar nenhuma única previsão. Se sentindo desamparado pelas suas habilidades, ele duvida de si e perde 1 Energia., além de ficar com Raiva ou Estresse ou Culpa.",
      "resultminus2": "Você recebe uma previsão que pode estar ou totalmente correta ou absurdamente errada.",
      "resultminus1": "Seu terceiro olho se recusa a abrir e dar qualquer insight que vá além dos sentidos.",
      "result0": "Sua clarividência parece bloqueada por alguma coisa, e precisará de algo externo para destravar.",
      "result1": "Você recebe uma resposta vaga e que possibilita muitas interpretações.",
      "result2": "Você receberá uma resposta minimamente precisa e específica, mas ainda aberta a interpretações.",
      "result3": "O Narrador lhe dá uma previsão precisa do presente, ou diz algo não muito obscuro ou aberto que deverá necessariamente ocorrer no futuro.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "PROTEGER OUTREM",
    "data": {
      "action": "PROTEGER OUTREM",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Defender outro ao invés de si mesmo.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação em Conjunto, Ação",
      "img_action_type": "-",
      "action_type1": "🛡",
      "action_type2": "⏫",
      "action_type3": "➕",
      "counter": [
        "ATK"
      ],
      "has_bonus": "Relação ou Afeto",
      "opp_has_bonus": "-",
      "action_condition": "Quanto mais forte a relação entre o protetor e o protegido, mais bônus.",
      "action_formula_lit": "SIM + Proficiência com Feitiço + Relação com Protegido + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Acaba agravando a investida do atacante, causando 2x o dano e efeito do ataque.",
      "resultminus2": "Você falha, deixando seu protegido vulnerável e você recebe um marcador de Culpa. Alvo fará uma ação de resistência caso não seja sua vez e não tiver tempo de agir.",
      "resultminus1": "Sua proteção não é capaz de barrar a investida do adversário, mas o ataque é levemente minimizado ao atravessar sua barreira (50% do dano e efeito).",
      "result0": "Você precisa improvisar a proteção utilizando alguma coisa externa. Se tiver sucesso com essa nova ação, seu alvo estará protegido com com o valor da proteção de bônus para defesa.",
      "result1": "Seu alvo fica protegido com 1x o \"dano\" de bônus para defesa.",
      "result2": "Seu alvo fica protegido com 2x o \"dano\" de bônus para defesa.",
      "result3": "O dano direcionado ao seu alvo será refletido para o atacante, ou você protege o seu alvo com sucesso e ganha uma nova vez para agir imediatamente.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "CURAR",
    "data": {
      "action": "CURAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Restaurar a saúde e tratar ferimentos, recuperando PdV e remover efeitos e condições.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "➕",
      "action_type2": "🛡",
      "action_type3": "-",
      "counter": [
        "Narração",
        "Maldição, Infligir Dor"
      ],
      "has_bonus": "Relação ou Afeto",
      "opp_has_bonus": "-",
      "action_condition": "Precisa ter os itens necessários.",
      "action_formula_lit": "SIM + Proficiência com Feitiço + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": " 1⚡*",
      "resultminus3": "Você piora o quadro do alvo. Ele perde 2x o \"dano\" e pode receber algum status negativo aleatório, como Ferido, Sangrando, Envenenado, etc. Você receberá 2 marcadores de Culpa.",
      "resultminus2": "Se atrapalha e não é capaz de curar o alvo. Acaba machucando-o um pouco mais, fazendo-o perder 1x \"dano\"",
      "resultminus1": "Causa dor no alvo, mas não é capaz de melhorar nem piorar a situação. Sentirá Culpa ou Estresse.",
      "result0": "Você percebe que para realizar a cura, necessitará de algo que não tem no momento.",
      "result1": "Alvo recupera 1 ponto de vida e limpa a condições básicas como Ferido, Sangrando, se não for algo grave demais.",
      "result2": "Alvo recupera até 1x o \"dano\" e perde algum efeito negativo, desde que com a poção ou feitiços corretos.",
      "result3": "Alvo recupera 2x o \"dano\" e perde efeitos negativos, desde que com a poção ou feitiços corretos. Fica estável até algum tratamento futuro.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "PERSUADIR",
    "data": {
      "action": "PERSUADIR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Convencer outros com argumentos.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Força de Vontade"
      ],
      "has_bonus": "Sensível",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "SIM + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Alvo não cede de forma alguma e na realidade se mostra ainda mais resistente à sua ideia do que estava originalmente. Agora Desconfiado, alvo resistirá a investidas futuras com +1d3",
      "resultminus2": "Alvo continua resistente e não cede.",
      "resultminus1": "Não estando convencido nem dissuadido, o alvo indica que precisa de algo para ser totalmente convencido.",
      "result0": "Alvo está resistente, porém aceita fazer uma pequena concessão.",
      "result1": "Alvo se mostra aberto a fazer uma consessão razoável.",
      "result2": "Alvo está praticamente convencido, e aceita ajudar, mas  não se torna um aliado.",
      "result3": "Alvo fica totalmente convencido da sua proposta e irá cooperar com você nas próximas ações.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "BARGANHAR",
    "data": {
      "action": "BARGANHAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Negociar acordos e trocas vantajosas.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "🔒",
      "action_type3": "-",
      "counter": [
        "Barganhar"
      ],
      "has_bonus": "Sensível",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "SIM + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "O alvo não aceita sua proposta de maneira nenhuma, e fica ofendido e hostil com a proposta.",
      "resultminus2": "A barganha não funciona muito bem, e você acaba tendo que pagar bem mais do que normalmente deveria se ainda quiser o item, e fica com Estresse ou Raiva.",
      "resultminus1": "Não dá muito certo, e você acaba tendo que pagar um pouco mais do que normalmente deveria se ainda quiser o item.",
      "result0": "Consegue apenas a promessa de que caso inclua mais um item o qual você não estava disposto a abrir mão haverá um trato feito.",
      "result1": "Consegue convencer o alvo a lhe oferecer o item por um preço razoável.",
      "result2": "Consegue convencer o alvo a lhe oferecer o item por um preço mínimo, e ainda ganhar algo mais como cortesia.",
      "result3": "Você se dá muito bem e faz um negócio muito vantajoso para você, que também parece ser muito vantajoso para seu alvo, que acaba ficando satisfeito quanto você.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "SEDUZIR",
    "data": {
      "action": "SEDUZIR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Encantar e atrair romanticamente.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação em Conjunto ",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Força de Vontade"
      ],
      "has_bonus": "Sensível",
      "opp_has_bonus": "Focado",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Alvo percebe sua investida e pode se tornar hostil. Seu personagem fica desmoralizado e envergonhado, e está mais sujeito a Intimidação por um tempo.",
      "resultminus2": "Não cai na sua investida, mas pode fingir que funcionou, só para lhe surpreender posteriormente, o que pode ou não acontecer.",
      "resultminus1": "Não cai na sua sedução, permanecendo indiferente às suas investidas.",
      "result0": "Percebe que está prestes a conseguir dar a cartada final para conquistar o alvo. Mas algo está faltando....",
      "result1": "Alvo fica interessado e está mais inclinado a fazer o que você pede.",
      "result2": "Alvo fica bastante interessado, mas vai ficar no seu pé, enquanto segue suas recomendações.",
      "result3": "Tem a total atração do alvo, que passa a cooperar com você e fazer praticamente tudo o que você recomenda.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "INSPIRAR",
    "data": {
      "action": "INSPIRAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Motivar e influenciar positivamente. Pode alterar a emoção de alguém para melhorar seus bônus.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "➕",
      "action_type3": "-",
      "counter": [
        "Narração",
        "Força de Vontade"
      ],
      "has_bonus": "Sensível, Afeto, Relação",
      "opp_has_bonus": "* Desregulado",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Você falha miseravelmente e acaba piorando o estado do seu alvo, o que te deixa com Culpa e,ou Estresse. Você gasta o dobro da Energia.",
      "resultminus2": "Seu alvo se sente inspirado e motivado, mas não tem nenhum bônus para fazer nada. Ele terá que fazer um teste de Força de Vontade. Se falhar, terá que tentar fazer o que você o inspirou, mesmo sem o bônus.",
      "resultminus1": "Sua tentativa não tem resultado no alvo, que lhe ignora veementemente.",
      "result0": "Não consegue de primeira, mas no meio do processo, você tem uma ideia clara de algo que possa funcionar para inspirar seu alvo. ",
      "result1": "Seu alvo está se sentindo um pouco mais inspirado, mas só terá 1d3 para fazer uma ação específica determinada pela Narração.",
      "result2": "Você consegue mudar uma emoção de todos os seus aliados ao redor, ocasionando neles poderem usar o bônus relacionado a esta emoção. ",
      "result3": "Consegue deixar as emoções do alvo do jeito que você quiser, dando o bônus quevem com ela. Seu alvo agora tem mais uma ação para realizar imediatamente.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "IMPLORAR",
    "data": {
      "action": "IMPLORAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Fazer pedidos fervorosos.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "💬",
      "action_type3": "-",
      "counter": [
        "Resistir Súplica",
        "Força de Vontade"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "SIM + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "O coração do seu adversário se endurece ainda mais, fortalecendo suas defesas contra qualquer tipo de convencimento em +3 de bônus.",
      "resultminus2": "Seu adversário não cede à sua súplica, continuando exatamente como antes.",
      "resultminus1": "Na medida que você implora, seu adversário faz um mínimo alívio ou concessão a seu favor.",
      "result0": "Seu adversário concorda em atender o que você suplica, porém por um preço ou favor.",
      "result1": "Seu adversário atende parcialmente a sua súplica, embora ainda bastante contrariado.",
      "result2": "Seu adversário atende a sua súplica, porém sem mudar de ideia totalmente.",
      "result3": "Seu adversário atende a sua súplica, e deixa de fazer o que estava fazendo, ou lhe dá o que você precisa, sem ressalvas. Além disso, ele ainda lhe ajuda com algo em seguida.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "ACALMAR",
    "data": {
      "action": "ACALMAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Pacificar indivíduos, ou acalmar criaturas. Pode alterar os sentimentos do alvo, dando-o bônus do sentimento em questão.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "➕",
      "action_type3": "⏫",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Sensível",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Deixa o alvo mais assustado, frenético, triste ou agressivo, dando-o +1d3 para as ações que condigam com as emoções que ele está apresentando.",
      "resultminus2": "A incapacidade de acalmar o alvo te desgasta, te deixando com Raiva e gastando 1 Energia.",
      "resultminus1": "Alvo não se afeta com sua tentativa de acalmá-lo.",
      "result0": "Você percebe o que iria deixar o alvo calmo.",
      "result1": "Alvo se acalma um pouco e deixa de ser uma ameaça, mas você fica apreensiv; um marcador de Desconfiado.",
      "result2": "Alvo fica calmo e você fica Satisfeito.",
      "result3": "Consegue deixar o alvo totalmente em paz e sereno, que ganha sua confiança e se mostra disposto a ajudar.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "DOMAR, TREINAR",
    "data": {
      "action": "DOMAR, TREINAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Controlar e treinar animais ou bestas.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Desafiar"
      ],
      "has_bonus": "Experiência em Criaturas",
      "opp_has_bonus": "seu personagem tiver Medo",
      "action_condition": "Tem bônus se usar Acalmar ou Intimidar a criatura antes.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "A criatura que você tenta domar fica ainda mais hostil ou amedrontada. Ela terá +3 de bônus para fugir ou atacar. Seu personagem gana um marcador de Medo.",
      "resultminus2": "A criatura fica resistente e desconfiada, e terá bônus de +2 para fugir ou atacar. Seu personagem ganha um marcador de Medo.",
      "resultminus1": "Você hesita justo antes de conseguir domar a criatura, perdendo o timing e a capacidade de ganhar a dominância dela.",
      "result0": "A criatura parece estar curiosa, e deve existir algo próximo que possa ajudar a ganhá-la totalmente.",
      "result1": "A criatura é dissuadida de atacar ou fugir, mas ainda permanece apreensiva.",
      "result2": "A criatura dá abertura, deixa inclusive ser tocada de leve, sem movimentos bruscos, mas não montada, nem oferecerá nenhum auxílio.",
      "result3": "A criatura se rende totalmente e confia em você, de forma que passa a ser sua aliada daí pra frente. ",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "CONTATOS",
    "data": {
      "action": "CONTATOS",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Conhecimento e acesso à rede de contatos.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "SIM + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Não conhece ninguém",
      "resultminus2": "Conhece alguém mas não consegue lembrar de onde ou como",
      "resultminus1": "Conhece alguém mas em algum lugar perigoso",
      "result0": "Conhece alguém em algum lugar longe ou inacessível no momento",
      "result1": "Conhece aguém que conhece alguém",
      "result2": "Conhece alguém ",
      "result3": "Conhece alguém próximo e com fácil acesso",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "RELAÇÃO",
    "data": {
      "action": "RELAÇÃO",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Determinar a natureza da relação entre personagens.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Você e o alvo são inimigos declarados. Tem -1d3 para ações de Simpatia, e ganha um marcador de Raiva ou Desconfiança. ",
      "resultminus2": "O alvo não gosta do seu personagem por algum motivo que você desconhece.",
      "resultminus1": "Conhece o alvo de vista e ele tem uma antipatia para com o seu personagem.",
      "result0": "Não conhece o alvo.",
      "result1": "Conhece o alvo de vista.",
      "result2": "Conhece o alvo de cumprimentar e ter uma conviência harmoniosa. Tem +1d3 ara ações de Simpatia com essa pessoa.",
      "result3": "Conhece e tem a confiança e estima do alvo. Tem +2d3 para ações de Simpatia com a pessoa. ",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "SENSIBILIDADE",
    "data": {
      "action": "SENSIBILIDADE",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "Perceber as emoções e intenções dos outros. “Leia” um personagem, identificando qual tipo de abordagem funcionará melhor, e intuindo quais temas podem ser atrativos ou sensíveis. ",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "🔍",
      "action_type3": "⏫",
      "counter": [
        "Oclumência"
      ],
      "has_bonus": "adv. tiver Afeto, ou Distraído",
      "opp_has_bonus": "Focado ou Desconfiado",
      "action_condition": "Aplica a condição Sensível, o que quer dizer que seu personagem está mais suscetível a entender com quem estiver interagindo.",
      "action_formula_lit": "SIM + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Não consegue identificar a resposta, mas acaba desenvolvendo um laço emocional unilateral, que o dificultará o seu personagem causar dano ao alvo, ou ficar quieto caso alguém o faça.\r\nSe Legilimência: Alvo percebe imediatamente que você está tentando penetrar sua mente e se torna hostil. A oclumência dele causa um efeito reverso em você que te deixa sob status Confundido.",
      "resultminus2": "Não consegue identificar nenhuma resposta útil.\r\nSe Legilimência: Alvo suspeita que você está tentando ler sua mente, e se fecha com oclumência com sucesso. ",
      "resultminus1": "Consegue identificar somente a emoção externa que o alvo está deixando passar.\r\nSe Legilimência: Encontra fragmentos confusos e desconexos que têm mais potencial para atrapalhar do que para ajudar.",
      "result0": "Desenvolve uma empatia e curiosidade pelo alvo, o que dará +1d3 para qualquer ação de Simpatia caso consiga interagir mais com ele. \r\nSe Legilimência: Ao não conseguir clareza na sua tentativa, você percebe que é necessária uma boa distração para conseguir a brecha que você precisa.",
      "result1": "Consegue identificar a resposta que buscava.\r\nSe Legilimência: Sua investida é capaz de extrair itens superficiais, que não estejam muito profundamente escondidos ou protegidos. O seu alvo saberá que você está usando legilimência.",
      "result2": "Consegue a resposta e de quebra identifica uma vontade a curto prazo do alvo, ou percebe o que o atrai ou repele.\r\nSe Legilimência: Você ultrapassa as defesas do alvo e consegue extrair itens profundos, porém em forma simbólica e não tão clara.",
      "result3": "Tem sua resposta, consegue identificar uma ambição intrínseca, um gosto ou amor essencial, ou um medo profundo facilmente, e tem +1d3 para rolagens de SIM com ele até ele mudar de emoção.\r\nSe Legilimência: Você consegue percorrer a mente do alvo como um lugar conhecido, extraindo exatamente o que você precisa, e sem deixar vestígios.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "LIDERAR, COORDENAR",
    "data": {
      "action": "LIDERAR, COORDENAR",
      "att": "SIM",
      "att_img": "❤️",
      "action_description": "-",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "➕",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Grupo Coeso",
      "opp_has_bonus": "Grupo Descordenado",
      "action_condition": "Organizar ações conjuntas, fazer com que um grupo aja de forma coordenada, aumentar a eficiência de aliados em táticas em grupo.",
      "action_formula_lit": "SIM + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Há hesitação e confusão; a ação em grupo tem -1d3 no total final",
      "resultminus2": "Os aliados se desentendem ou agem em momentos errados. A ação coletiva falha e gera problemas (como atraso, ruído, dispersão).",
      "resultminus1": "A coordenação é fraca; cada um age por conta própria. Apenas um aliado executa a ação como esperado...",
      "result0": "Os aliados executam a ação, mas sem benefícios extras. Independente do tipo de ação, apenas o valor do personagem mais alto vale.",
      "result1": "A ação coordenada soma todos os valores dos participantes ou média (se for o caso) normalmente.",
      "result2": "Além da soma normal, o grupo ganha +1d3 bônus no total.",
      "result3": "Execução perfeita; além da soma e bônus, o grupo pode agir novamente, ou, se for fora de combate, ficam Inspirados por três ações.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "MIRAR",
    "data": {
      "action": "MIRAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Apontar com precisão. Executar algum ataque a um lugar específico, que tenha mais a ver com precisão do que com força. Gastar uma ação com MIRAR garante bônus em certas ações seguintes.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação, Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "Focado",
      "opp_has_bonus": "Em movimento",
      "action_condition": "Precisa não estar sob efeito de Raiva ou Estresse, ou ter tido sucesso em Focaar antes. Pode ser usada como oposto de DESVIAR, na forma Rolagem Passiva.",
      "action_formula_lit": "RAZ + Proficiência com Feitiço ou Arma + Bônus + 1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Erra feio e acaba acertando algo que causa problemas, como quebrando algo valioso ou perigoso, ou machucando alguém ou a si.",
      "resultminus2": "Erra e sua varinha ou arma cai no chão, perto de você.",
      "resultminus1": "Erra por um triz.",
      "result0": "Acerta de raspão.",
      "result1": "Acerta numa região não muito séria, causa Efeito Menor .",
      "result2": "Acerta numa região importante mas não crítica, causa Efeito.",
      "result3": "Acerta em cheio, causando Dano + Efeito Extra.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "PROTEGER-SE",
    "data": {
      "action": "PROTEGER-SE",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Criar ou usar escudos para defender-se contra ameaças.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🛡",
      "action_type2": "⏫",
      "action_type3": "⭯",
      "counter": [
        "ATK"
      ],
      "has_bonus": "Alerta",
      "opp_has_bonus": "-",
      "action_condition": "Com sucesso +2 e crítico, não perde a vez, tendo a chance de revidar.",
      "action_formula_lit": "RAZ + Proficiência com Feitiço ou Arma, Valor de DEF + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Você erra e não consegue gerar a proteção, recebendo o ataque em cheio. E fica Atordoado na próxima rodada, ou recebe dano extra. Ou faz sua proteção e não percebe que ela é inútil.",
      "resultminus2": "Você erra e não consegue gerar a proteção, recebendo o ataque em cheio. Ou faz sua proteção e percebe que ela é inútil.",
      "resultminus1": "Você faz uma proteção não muito eficaz, e o ataque inimigo lhe atinge, porém com menor efeito (50%) ao passar pelo escudo.",
      "result0": "Você faz uma proteção não muito eficaz, que ocorre num resultado inesperado.",
      "result1": "Se protege do ataque por um triz. Seu escudo se quebra no final na investida do adversário, dando a ele a vez.",
      "result2": "Sua proteção consegue refletir 50% do ataque com sucesso. Se for uma proteção não instantânea, ela continua ativa.",
      "result3": "Você consegue não somente refletir o ataque, como também ganha uma vez extra para agir em sequência. Se for uma proteção não-instantânea, ela permanece ativa pelo dobro do tempo.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "FOCAR",
    "data": {
      "action": "FOCAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Concentração mental e precisão. Ao gastar uma ação com FOCAR, havendo sucesso, ganha a condição Focado, que dá bônus  em certas ações seguintes.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação, Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "⏫",
      "action_type3": "⭯",
      "counter": [
        "Distrair",
        "Narração"
      ],
      "has_bonus": "Calma",
      "opp_has_bonus": "-",
      "action_condition": "Ação para obter a condição FOCADO, gasta duas energias. Na modalidade Rolagem Passiva, é a defesa contra DISTRAIR e não gasta energia.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Fica mais confuso e frustrado. Estresse ou Culpa. Se passivo, não percebe o que está vindo e encontra-se na condição DISTRAÍDO, mais vulnerável a ataques. Se estiver executando um feitiço, algo sai errado e machuca a si, a alguém ou algo no ambiente.",
      "resultminus2": "Não é capaz de focar, não conseguindo realizar a atividade, mas sem deixar nenhum efeito adverso.",
      "resultminus1": "Ao focar, fica vulnerável a surpresas externas. Se estiver realizando um feitiço, pode escolher gastar a próxima vez para completar a ação com Sucesso (+2) ou aceitar a falha e não perder sua próxima vez.",
      "result0": "Alterna entre o foco e a distração, e para focar de verdade vai precisar de ajuda, seja mudando de local, ou de algum feitiço ou poção. Se realizando um feitiço, não consegue controle total, produzindo um efeito aquém do esperado.",
      "result1": "Gastando +1 Energia, consegue focar, e conseguir o resultado do Sucesso (+2).",
      "result2": "Segue compenetrado apesar das distrações. Se realizando feitiço, consegue efeito e controle parcial.",
      "result3": "Está totalmente focado e obstinado no seu propósito, impossível de ser distraído e receberá +1d3 para a próxima ação utilizando esse foco. Se estiver fazendo um feitiço, consegue seu efeito e controle total.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "ENFEITIÇAR, DESENFEITIÇAR",
    "data": {
      "action": "ENFEITIÇAR, DESENFEITIÇAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Feitiços de controle ou modificação de propriedades, usando Razão.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "💬",
      "action_type3": "🔒",
      "counter": [
        "DEF"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "RAZ + Proficiência do Feitiço ou Arma + Bônus +  1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Realiza o feitiço errado, causando um efeito adverso, muito ruim para si, e muito vantajoso para o adversário.",
      "resultminus2": "Realiza o feitiço errado, causando um efeito adverso.",
      "resultminus1": "Não consegue produzir o feitiço.",
      "result0": "Consegue um efeito inesperado que lhe ajuda mas também atrapalha.",
      "result1": "Menor Efeito do feitiço.",
      "result2": "Efeito do feitiço.",
      "result3": "Efeito Extra do feitiço.",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "TRANSFORMAR",
    "data": {
      "action": "TRANSFORMAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Mudar a forma de objetos ou seres, e usá-los em seguida.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💎",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "Narração",
        "ATK"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "RAZ + Proficiência com Feitiço + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Acidentalmente causa uma explosão mágica ou cria um resultado deformado e desastroso e errante que afeta negativamente todos os próximos à área.",
      "resultminus2": "Produz algo que, se animado, se revolta contra o jogador. Se não animado, causa uma explosão ou barulho que alerta inimigos próximos ou causa algum tipo de atrapalho.",
      "resultminus1": "A transformação não é bem-sucedida, mas o jogador não sofre lesões. Perde 1 Energia além do normal.",
      "result0": "Produz uma versão básica da transformação, que não cumpre os efeitos desejados totalmente mas também não se volta contra si, e também não tem o item transformado sob seu controle. Por 1 Energia,  jogador ganha a chance continuar com a vez para reparar e melhorar a situação.",
      "result1": "O jogador transforma o objeto ou ser com sucesso, mas o item não está necessariamente sob seu controle.",
      "result2": "A transformação é bem competente, permitindo que o controle suficiente do o objeto ou ser transformado.",
      "result3": "Realiza uma transformação perfeita com não somente os efeitos desejados, como efeitos acidentais positivos. Obtém também total domínio sobre o objeto ou ser.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "CONFECCIONAR, REPARAR",
    "data": {
      "action": "CONFECCIONAR, REPARAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Conjurar, confeccionar ou consertar itens.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💎",
      "action_type2": "➕",
      "action_type3": "⭯",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Conhecimento",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "RAZ + Proficiência com Feitiço ou Ferramentas + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "O item que você consegue produzir não serve para nada e causa problemas sérios. Você gasta 1 Energia além do normal.",
      "resultminus2": "Seu personagem não consegue terminar o item, e perde 2 Energia no processo, além de ficar com Estresse ou com Raiva.",
      "resultminus1": "Seu personagem não sabe, mas o item que produziu pode causar problemas. Seu personagem é obrigado a usá-lo, já que não sabe que ele está defeituoso.",
      "result0": "Sua obra fica inacabada ou instável. Ainda pode servir, mas não é confiável e poderá causar algum problema sério. Ou você consegue terminá-la mas gasta muito tempo.",
      "result1": "O item produzido consegue fazer 50% do propósito desejado. Você gasta 1 Energia além do necessário.",
      "result2": "O item produzido fnalizado é capaz de fazer 75% do propósito desejado.",
      "result3": "O item é produzido com sucesso e serve bem para o fim desejado.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "PERCEPÇÃO",
    "data": {
      "action": "PERCEPÇÃO",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Perceber detalhes e enganações, de forma passiva.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "🔒",
      "action_type3": "⏫",
      "counter": [
        "Narração",
        "Enganar"
      ],
      "has_bonus": "Alerta",
      "opp_has_bonus": "Escondido",
      "action_condition": "Rolagem Passiva: O narrador solicita uma rolagem para saber se o personagm percebeu algo.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Não é capaz de identificar se está sendo enganado ou se é um blefe. Não tem nenhuma pista ou evidência. Tem tendência a concordar com o outro. Recebe um marcador de Afeto para com o interlocutor, dificultando sua resistência a ele.",
      "resultminus2": "Não é capaz de identificar se está sendo enganado ou manipulado. ",
      "resultminus1": "Fica desconfiado, mas não é capaz de identificar vestígios ou enganação.",
      "result0": "Receberá uma resposta vaga do Narrador.",
      "result1": "É capaz de identificar que está sendo enganado. Nota algo vago no ar. Ganha um marcador de Desconfiança ou a condição Alerta.",
      "result2": "Faz uma boa leitura da pessoa, da situação ou do ambiente, e receberá uma dica do narrador suficientemente reveladora. Ganha um marcador de Desconfiança ou a condição Alerta.",
      "result3": "É capaz de resistir a qualquer investida de Enganação ou armadilha, percebendo detalhes nas entrelinhas da mentira. Ganha um marcador de Desconfiança ou a condição Alerta.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "INVESTIGAÇÃO",
    "data": {
      "action": "INVESTIGAÇÃO",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Observar detalhes e detectar sutilezas em ambientes e vestígios de magia.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "💎",
      "action_type3": "⏫",
      "counter": [
        "-"
      ],
      "has_bonus": "Calma",
      "opp_has_bonus": "Furtividade",
      "action_condition": "Jogador escolhe a Dificuldade e deverá alcançá-la. Havendo sucesso, terá a resposta referente àquela Dificuldade.",
      "action_formula_lit": "RAZ + Familiaridade + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": " 1-3⚡",
      "resultminus3": "Entende pistas falsas, o que fará o personagem receber um dado a menos em qualquer rolagem até fazer o que o seu personagem inferiu erroneamente.",
      "resultminus2": "Não consegue identificar as respostas para as suas perguntas para o Narrador.",
      "resultminus1": "Recebe um marcador de Desconfiança (se estiver lidando com pessoas), mas não é capaz de identificar vestígios.",
      "result0": "Receberá uma resposta vaga do Narrador. Recebe a condição Alerta ou um marcador de Desconfiança.",
      "result1": "Receberá uma resposta do narrador, ainda que pouco esclarecedora. Recebe a condição Alerta se relevante.",
      "result2": "Receberá uma resposta do narrador não exatamente precisa, porém suficientemente reveladora. Recebe a condição Alerta se relevante.",
      "result3": "Consegue identificar magia ou rastros com mestria, recebendo respostas precisas e práticas do Narrador. Recebe a condição Alerta se relevante.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "OCLUMÊNCIA",
    "data": {
      "action": "OCLUMÊNCIA",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Proteger a mente contra leituras indesejadas.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Sensibilidade"
      ],
      "has_bonus": "Desconfiança",
      "opp_has_bonus": "o seu Afeto",
      "action_condition": "-",
      "action_formula_lit": "RAZ + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "2⚡",
      "resultminus3": "Dá total abertura pra leitura da mente e possessão. Estresse ou Raiva. -1 Energia.",
      "resultminus2": "Seu atacante identifica sua tentativa de bloqueiro, a dribla, e consegue informações mais precisas embora não a história toda.",
      "resultminus1": "Você fecha sua mente, mas deixa escapar algum detalhe vago que o seu atacante esteja buscando.",
      "result0": "Sua mente se fecha e fica impossível de extrair algo dela, mas apenas enquanto o seu personagem estiver totalmente concentrado.",
      "result1": "O seu atacante não consegue alcancar suas memórias e sentimentos mais íntimos, apenas os superficiais.",
      "result2": "Sua mente fica protegida de qualquer leitura, mas o seu atacante vai ter certeza que você está bloqueando a mente para ele.",
      "result3": "Sua mente fica blindada e impenetrável, embora possa parecer que está vulnerável caso você queira, não deixando o alvo perceber que a tentativa dele de legilimência não deu certo. ",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "BUSCAR",
    "data": {
      "action": "BUSCAR",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Encontrar informações ou objetos.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "💎",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Mais de uma pessoa",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "2-5⚡",
      "resultminus3": "Não encontra absolutamente nada útil e ainda faz uma bagunça e perde 2 Energia. Ganha 1 medidor de Estresse.",
      "resultminus2": "Não encontra o que busca, tendo certeza que não está aí (embora esta certeza condiga ou não com a realidade). Perde 1 Energia. ",
      "resultminus1": "Não encontra o que busca, mas fica muito interessado na busca, perdendo os próximos minutos de ação.",
      "result0": "Encontra pistas de onde pode encontrar o que busca.",
      "result1": "Encontra algo vago e razoavelmente útil, ou parte do que busca apenas.",
      "result2": "Encontra algo útil e relativamente completo ou específico.",
      "result3": "Caso esteja disponível no local, encontra exatamente o que procurava, e ainda encontra algo além que pode ajudar grandemente. ",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "APRENDER",
    "data": {
      "action": "APRENDER",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Absorver novos conhecimentos através de leitura, aulas ou estudo.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "2-5⚡",
      "resultminus3": "Não consegue aprender o tópico novo de maneira nenhuma. É incapaz de realizar ações com ele, e se tentar irá se machucar ou machucar alguém. Fica frustrado; com Raiva ou Estresse. Gasta 2 Energia.",
      "resultminus2": "Não aprende o suficiente para realizar algo com o conhecimento. Gasta 1 Energia.",
      "resultminus1": "Não é capaz de aprender nada além do básico. Se tentar usar o conhecimento, terá uma dedução de -1d3.",
      "result0": "Ainda falta algo para finalizar o aprendizado básico desse conceito.",
      "result1": "Aprende o básico, para conseguir realizar a ação, porém sem nenhum bônus, e ainda gastará 1 Energia com a dificuldade do principiante.",
      "result2": "Aprende o tópico de forma a não gastar energia ao tentar realizá-lo.",
      "result3": "Consegue adquirir o conhecimento com facilidade, podendo de agora em diante usar +1d3 com rolagens relacionadas a este assunto.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "CONHECIMENTO",
    "data": {
      "action": "CONHECIMENTO",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Saber ou conhecer algum assunto.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "⏫",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "É completamente ignorante nesse assunto. Tem um bloqueio total, e se tentar fazer alguma coisa nesta área, vai ter dedução de -1d3 e perder 1 energia.",
      "resultminus2": "Não sabe nenhuma informação útil. Ganha um marcador de Culpa ou Estresse.",
      "resultminus1": "Sabe alguns fragmentos muito imprecisos que não servem pra muita coisa. Perde 1 energia.",
      "result0": "Já ouviu falar, mas precisa de algo para ajudar a lembrar. Um livro, uma conversa, etc.",
      "result1": "Sabe por alto algum detalhe útil.",
      "result2": "Conhece até o nível intermediário do assunto.",
      "result3": "Expert no assunto. Sabe de cabeça e sem dificuldades. +1d3 para qualquer ação que tente fazer com este conhecimento.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "RESOLVER ENIGMA",
    "data": {
      "action": "RESOLVER ENIGMA",
      "att": "RAZ",
      "att_img": "⚙️",
      "action_description": "Resolver puzzles, charadas e mistérios.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "🔍",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": " 2⚡",
      "resultminus3": "Jogador estraga o enigma, invalidando-o ou agora tendo que lidar com o fato de tê-lo arruinado, inimigos podem aparecer ou o caminho ser bloqueado de vez.",
      "resultminus2": "Jogador ganha um medidor de Estresse e perde 1 Energia",
      "resultminus1": "Enigma fica mais difícil, ou joador perde 1 Energia",
      "result0": "Receberá um breve missão para conseguir uma dica",
      "result1": "Recebe uma dica vaga do narrador.",
      "result2": "Recebe uma boa dica do narrador",
      "result3": "Recebe a resposta certa do narrador",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "MALDIÇÃO, INFLIGIR DOR",
    "data": {
      "action": "MALDIÇÃO, INFLIGIR DOR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Usar maldições, ou causar sofrimento físico ou emocional.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "Raiva, Satisfação",
      "opp_has_bonus": "-",
      "action_condition": "Precisa haver Raiva ou Satisfação. Esta modalidade de combate foca em causar DANO e EFEITO EXTRA.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Algo dá errado na sua maldição ou tentativa de machucar e volta em você com a mesma intensidade que você tinha intencionado ao alvo.",
      "resultminus2": "Você gasta muita energia para tentar realizar esse feito, mas não dá certo, causando você gastar energia à toa. (2 Energias).",
      "resultminus1": "Seu personagem não consegue realizar ação de forma que cause algum efeito, lhe deixando com Culpa, com Raiva ou Estresse.",
      "result0": "Não produz nenhum efeito.",
      "result1": "Causa apenas o Efeito normal da maldição ou machucado pelo tempo e intensidades 'originais'.",
      "result2": "Sua maldição ou golpe dá certo, causando Dano + Efeito Extra, e lhe dando a condição de Satisfeito.",
      "result3": "Causa dor e sofrimento imediatos, deixando a vítima com sérios efeitos por tempo prolongado. (2x Dano + Efeito Extra)",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "AZARAR",
    "data": {
      "action": "AZARAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Use feitiços de controle ou modificação de propriedades, como Jinxes e Hexes, que causam desconforto e efeitos negativos ao alvo. \r\n",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "Conhecimento em Transfiguração ou Feitiços pode afetar bônus.\r\nPode causar diversas Condições no alvo.",
      "action_formula_lit": "MAL + Proficiência com Feitiço ou Arma + Bônus +  1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Realiza o feitiço errado, causando um efeito adverso, muito ruim para si, e muito vantajoso para o adversário.",
      "resultminus2": "Realiza o feitiço errado, causando um efeito adverso.",
      "resultminus1": "Não consegue produzir o feitiço.",
      "result0": "Consegue um efeito inesperado que lhe ajuda mas também atrapalha um pouco.",
      "result1": "Dano + Menor efeito ou rápido efeito",
      "result2": "Dano + Efeito",
      "result3": "Dano + Efeito Extra",
      "action_group_possib": "🤝",
      "action_detail": "-"
    }
  },
  {
    "id": "DESVIAR",
    "data": {
      "action": "DESVIAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Esquivar-se de golpes. Obriga o adversário a fazer um teste de MIRAR. ",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🛡",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "Mirar"
      ],
      "has_bonus": "Renunciar a próxima vez",
      "opp_has_bonus": "Focado",
      "action_condition": "Esta modalidade de combate foca em evitar DANO, e tentar garantir a próxima vez. \r\nBônus:\r\n+ Se já estiver em movimento antes;\r\n+ Se sacrificar sua próxima ação;\r\n- Se estiver sob algum efeito negativo que envolva a capacidade de movimento;",
      "action_formula_lit": "MAL + Velocidade + Bônus + 1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Recebe o impacto em cheio, em um ponto vulnerável, recebendo 2x o Dano determinado no acerto crítico do ataque.",
      "resultminus2": "Recebe o golpe numa região não muito importante, mas inconveniente o suficiente para causar dano e consequências. Além disso, vale também o resultado Sucesso (+2) do atacante.",
      "resultminus1": "Recebe o golpe de raspão, com efeitos mínimos (menos de 50%). Ver o resultado Sucesso Simples (+1) do atacante.",
      "result0": "Só irá conseguir desviar ou bloquear se mexer no ambiente, lançando algo na frente ou mudando de posição drasticamente. Ganha mais uma ação para tentar.",
      "result1": "Por pouco, consegue se esquivar totalmente, gastando sua vez. Recebe o Status EM MOVIMENTO.",
      "result2": "Consegue desviar numa bela esquiva e tem +1d3 na próxima ação.",
      "result3": "Não somente consegue desviar como está na posição perfeita e com tempo suficiente para contratacar. Ganha mais uma vez. ",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "EMBOSCAR",
    "data": {
      "action": "EMBOSCAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Funciona como se fosse a ação SURPREENDER mais um ATAQUE.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⚔",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "DEF"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "Só é possível se alvo não estiver esperando (você está escondido, ou seu alvo não está interagindo com você, ou é um feitiço ou ação inusitados).",
      "action_formula_lit": "MAL + Proficiência com Feitiço ou Resultado da Armadilha + Bônus +  1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "Seu adversário,alvo é alertado e e corta na sua vez, neutralizando a sua.",
      "resultminus2": "Seu adversário fica desconfiado e tem +1d3 para Proteger.",
      "resultminus1": "Erra a execução, gastando a vez à toa.",
      "result0": "Percebe que não é a hora ideal para dar o bote, hesitando. Mas terá +1d3 na próxima vez, caso não saia desse estado de atenção pronto para atacar.",
      "result1": "Efeito curto ou menor",
      "result2": "Realiza o efeito comum do feitiço ou golpe",
      "result3": "Dano + Efeito, e seu personagem ganha uma vez.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "SURPREENDER",
    "data": {
      "action": "SURPREENDER",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Realizar emboscadas e ataques furtivos, ou ou pegar alguém de surpresa. Use combinado com um ação inusitada, inesperada, armadilha ou golpe baixo.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação em Conjunto",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "Percepção"
      ],
      "has_bonus": "Escondido",
      "opp_has_bonus": "Alerta",
      "action_condition": "Personagens SURPREENDIDOS têm menos um dado para se defender, e podem perder o FOCO.\r\n\r\nEsta també é uma ação bônus ao usar feitiços não-verbais. ",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Se atrapalha e se revela antes da surpresa, deixando o inimigo mais preparado que você. Você perde sua próxima ação e você terá -1d3 na ação seguinte.",
      "resultminus2": "Deixa o inimigo suspeito antes da sua emboscada. Ele não se surpreende com o susto, e na realidade fica mais preparado ainda, ganhando +1d3 na sua próxima ação.",
      "resultminus1": "O inimigo fica surpreso, mas consegue se preparar para se defender a tempo. Você só conseguirá Emboscar ou o bônus da surpresa se tirar pelo menos +2 na ação principal.",
      "result0": "Você não se sente pronto para sua emboscada. Providencie mais algum elemento para tentar distrair o alvo. Você ganha mais uma ação para tentar isso.",
      "result1": "Surpreende o inimigo, que perderá uma rodada para tentar se defender.",
      "result2": "Pega o inimigo desprevenido, que perderá a vez, e você terá +1d3 na próxima ação.",
      "result3": "Pega o inimigo totalmente desprevenido e sem estar com a arma pronta na mão. Você ganha +1d3 nas próxima ação, e seu dano será duplicado caso seja uma ação com dano.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "DISTRAIR",
    "data": {
      "action": "DISTRAIR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Desviar a atenção de outros, interrompendo seu FOCAR, ou preparando algém para SURPREENDER, ao criar uma distração proposital.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "⭯",
      "action_type3": "-",
      "counter": [
        "Focar"
      ],
      "has_bonus": "Escondido",
      "opp_has_bonus": "Focado",
      "action_condition": "Personagens DISTRAÍDOS têm menos um dado para se defender de ataques aos quais não estão atentos.",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Seu alvo fica mais focado do que antes, e ao tentar distraí-lo, você perde o foco e fica vulnerável a ataques -1d3 para ações relacionadas com Percepção ou Proteger-se.",
      "resultminus2": "Seu alvo não perde o Foco e permanece executando sua ação, ciente da sua interferência, e preparado para reagir enquanto mantém seu Foco.",
      "resultminus1": "No intuito de distrair ou confundir, você obtém um pequeno sucesso contra o alvo, mas algo dá errado pra você.",
      "result0": "A atenção do alvo titubeia e o faz parar por alguns segundos o que está fazendo e sofrer os efeitos em questão, abrindo espaço para uma ação decisiva, mas retornará à ação caso nada com sucesso seja feito imediatamente.",
      "result1": "Você consegue fazer o seu alvo perder o Foco que está tentando manter e interromper o processo dele em curso por um tempo.",
      "result2": "O alvo é distraído e comete um erro devido à sua interferência.",
      "result3": "Seu alvo perde totalmente o Foco e estraga o que estava fazendo completamente.",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "FUGIR",
    "data": {
      "action": "FUGIR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Escapar de perseguições ou situações perigosas. seu inimigo, casoqueira apanhá-lo, vai usar as ações ao lado:",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "🛡",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "ATK",
        "Iniciativa, Alcançar"
      ],
      "has_bonus": "Medo",
      "opp_has_bonus": "Raiva",
      "action_condition": "-",
      "action_formula_lit": "MAL + Velocidade + Bônus + 1d3Fixo\r\n",
      "action_formula_array": "-",
      "action_energy": "3⚡",
      "resultminus3": "Cai e se machuca, perdendo pelo menos 1 Energia e 1 Ponto de Vida. Se for aparatando, poderá se estrunchar. É encurralado ou capturado com facilidade.",
      "resultminus2": "Após uma breve perseguição, é finalmente encurralado. Se for aparatando, tem receio de aparatar no local por perceber alguma proteção ou risco de estrunchamento.",
      "resultminus1": "Fica preso em alguma coisa na tentativa de fugir, mas ainda não foi encurralado ou capturado totalmente.",
      "result0": "Está prestes a fugir, mas algo ocorre que lhe faz hesitar. Voê ainda pode escolher fugir ou não, porém deixando rastros e sendo percebido que fugiu.",
      "result1": "Foge por pouco, deixando vestígios.",
      "result2": "Foge com sucesso, despistando o inimigo.",
      "result3": "Foge com folga, sem deixar nenhum rastro óbvio ou fácil de ser seguido.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "ENGANAR",
    "data": {
      "action": "ENGANAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Ludibriar e iludir outros com algo que seu personagem sabe que não é verdadeiro.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Percepção"
      ],
      "has_bonus": "Adversário tiver Afeto, ou for Seduzido",
      "opp_has_bonus": "Desconfiado",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Alvo não fica convencido e se torna hostil. Culpa ou Estresse.",
      "resultminus2": "Você não consegue convencer o alvo, que te manda embora ou vai embora.",
      "resultminus1": "Você não consegue convencer o alvo, que permanece no ambiente como um obstáculo ou inimigo.",
      "result0": "O alvo acredita em partes do que você disse, mas precisa de algo mais para ser convencido.",
      "result1": "O alvo acredita no que você disse, mas fica desconfiado e com a guarda levantada daí em diante.",
      "result2": "Você convence o alvo, que acredita suficientemente na sua mentira por uma vez e deixa você em paz.",
      "result3": "Você convence o alvo, que cai totalmente no seu papo. Ele fica mais propenso a seguir suas direções depois disso. ",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "MANIPULAR",
    "data": {
      "action": "MANIPULAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Controlar mentes ou influenciar ações. Permite também modificar as emoções de alguém, fazendo-as receber o (b)ônus das emoções relevantes.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💬",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Percepção",
        "Força de Vontade"
      ],
      "has_bonus": "Adversário tiver Afeto, ou for Seduzido",
      "opp_has_bonus": "Desconfiado",
      "action_condition": "Permite também modificar as emoções de alguém, fazendo-as receber o ônus das emoções relevantes.",
      "action_formula_lit": "MAL + Relação com Sujeito + Bônus + 1d3Fixo",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Alvo se torna hostil, percebendo a tentativa de manipulação. Agora um inimigo, ele terá +1d3 para sua próxima ação.",
      "resultminus2": "Alvo se torna hostil, percebendo a tentativa de manipulação com clareza. ",
      "resultminus1": "Alvo fica desconfiado de que você pode o estar manipulando, e a sua confiança se perde. Ele não aceita sua proposta.",
      "result0": "Alvo cai na sua lábia parcialmente e fica disposto a fazer uma pequena consessão, porém ciente de seu jogo-sujo e se demosntra a contra-gosto, o que pode significar que ele ainda pode agir contra você.",
      "result1": "Alvo toma consciêncida de que está sendo manipulado, mas tenta entrar no jogo para ver se tem algo a ganhar com a situação.",
      "result2": "Alvo aceita sua investida e fica disposto a fazer uma consessão. Você consege mudar uma emoção do alvo, deixando-o com bônus negativo por conta desta emoção.",
      "result3": "Além do sucesso do convencimento, o alvo não tem a menor ideia de que está sendo manipulado, e topa ajudá-lo com praticamente qualquer coisa daí em diante. Você consege mudar totalmente as emoções do alvo, deixando-o com bônus negativo das emoções mencionadas. ",
      "action_group_possib": "⚖️",
      "action_detail": "-"
    }
  },
  {
    "id": "RESISTIR SÚPLICA",
    "data": {
      "action": "RESISTIR SÚPLICA",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Não ceder a pedidos ou apelos emocionais.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Rolagem Passiva",
      "img_action_type": "-",
      "action_type1": "🔒",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Implorar"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "Satisfação",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Você não consegue continuar e cede imediatamente, se sentindo com Culpa e perdendo 1 Energia.",
      "resultminus2": "Você não resiste ao pedido e acaba cedendo.",
      "resultminus1": "Você insiste mas acaba cedendo, após concordar com uma concessão.",
      "result0": "Você se mantém inafetado à súplica, mas sente Culpa inevitavelmente.",
      "result1": "Seu alvo implora, mas você segue firme na sua resolução, porém alivia um pouco o que está causando a súplica e ganha um medidor de Culpa.",
      "result2": "Você mantém sua cabeça, inalterado pela súplica.",
      "result3": "Você permanece intransigente quanto ao que lhe estão suplicando. Ganha também um marcador de Satisfeito.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "FURTIVIDADE",
    "data": {
      "action": "FURTIVIDADE",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Mover-se silenciosamente e passar despercebido.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "⏫",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Percepção",
        "Clarividência"
      ],
      "has_bonus": "estiver Escuro",
      "opp_has_bonus": "Alerta",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "1⚡",
      "resultminus3": "É detectado por todos os inimigos imediatamente, se machucando no processo.",
      "resultminus2": "É detectado por pelo menos um inimigo, que sabe exatemente onde você está.",
      "resultminus1": "É detectado por um inimigo, que estará alerta e que deverá fazer uma rolagem de percepção para encontrar você.",
      "result0": "A presença de alguém é detectada pelos inimigos, mas não sabem exatamente onde nem o que.",
      "result1": "Sua presença é detectada, mas um inimigo acha que você é um deles ou algum item do ambiente, o que não deixa a pessoa alerta. Ela poderá interagir à distância e acabar revelando algum detalhe útil para você.",
      "result2": "Se continuar se movendo de maneira comedida, continuará indetectado pelos inimigos.",
      "result3": "Consegue se mover completamente indetectado, tendo +1d3 para Surpreender, Intimidar ou Distrair em seguida.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "ROUBAR, PLANTAR",
    "data": {
      "action": "ROUBAR, PLANTAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Pegar ou esconder itens sem ser detectado.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "💎",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Percepção",
        "Narração"
      ],
      "has_bonus": "Escondido",
      "opp_has_bonus": "Alerta, Desconfiado",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "É percebido pelo inimigo imediatamente.",
      "resultminus2": "Não consegue pegar o item, mas deixa o inimigo desconfiado. Outrém deverá distraí-lo imediatamente antes que ele perceba e fique hostil, na maioria das vezes.",
      "resultminus1": "Não consegue pegar o item, mas também não é notado. ",
      "result0": "Consegue pegar,plantar o item, mas deixa o inimigo desconfiado. Deverá distraí-lo imediatamente antes que ele perceba.",
      "result1": "Consegue pegar,plantar o item, sem este detectar que você foi quem roubou,plantou, mas dentro de alguns momentos ele irá perceber que o item está faltando,nele, porém sem necessariamente desconfiar de você.",
      "result2": "Consegue pegar ou depositar o item sem nenhuma detecção.",
      "result3": "Consegue pegar ou depositar o objeto sem nenhuma detecção e ainda encontra mais algo de bônus.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "MANUSEAR",
    "data": {
      "action": "MANUSEAR",
      "att": "MAL",
      "att_img": "𖦹",
      "action_description": "Lidar com mecanismos e dispositivos.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação",
      "img_action_type": "-",
      "action_type1": "-",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "Calma",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Não consegue utilizar o item e ele se quebra no processo, ficando inutilizável.",
      "resultminus2": "Não consegue utilizar as mãos para o fim desejado e se machuca com o item.",
      "resultminus1": "Você consegue manusear o item para realizar seu objetivo, mas danifica o item no processo, ou consegue manuseá-lo corretamente apenas depois de muito tempo.",
      "result0": "Tem alguma coisa faltando para que você consiga manusear o item corretamente; você precisa de uma outra ideia.",
      "result1": "Você consegue usar o item de forma satisfatória depois de algumas tentativas, conseguindo realizar a atividade, mas gastando 1 Energia.",
      "result2": "Você é capaz de manusear o item de forma satisfatória.",
      "result3": "Você manuseia o item com maestria e destreza, realizando perfeitamente a atividade desejada.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "RECURSOS",
    "data": {
      "action": "RECURSOS",
      "att": "-",
      "att_img": "-",
      "action_description": "Ação para descobrir se o personagem tem algo que precisa e que não foi mencionado na narração ainda.",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "Ação Bônus",
      "img_action_type": "-",
      "action_type1": "💎",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Narração"
      ],
      "has_bonus": "for Coerente",
      "opp_has_bonus": "-",
      "action_condition": "-",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Não tem o item e tem azar em relação a ele: terá -1d3 em qualquer rolagem daqui pra frente com o intuito de adquirir este item.",
      "resultminus2": "Não tem, mas pode conseguir se fizer algo desafiador ou distante.",
      "resultminus1": "Não tem, mas pode conseguir se fizer algo simples.",
      "result0": "Tem o item que precisa, mas não está com você agora.",
      "result1": "Tem o item que precisa, mas não é seu ou não está em bom estado ou é falso.",
      "result2": "Tem o item que precisa.",
      "result3": "Tem não só isso como tem mais algo muito valioso.",
      "action_group_possib": "❌",
      "action_detail": "-"
    }
  },
  {
    "id": "NARRAÇÃO",
    "data": {
      "action": "NARRAÇÃO",
      "att": "-",
      "att_img": "-",
      "action_description": "3 - Trivial (realizável sem esforço significativo); 6 - Moderado (exige atenção e um pouco de habilidade); 9 - Desafiador; 12 - Difícil (exige esforço considerável para ser alcançado); 15 - Dificílimo; 18 - Hercúleo (extremamente difícil, exige habilidades extraordinárias); 21 - Impraticável (possível na teoria, mas quase impossível na prática)",
      "icon_action": "-",
      "img_action": "-",
      "action_type": "-",
      "img_action_type": "-",
      "action_type1": "-",
      "action_type2": "-",
      "action_type3": "-",
      "counter": [
        "Jogador"
      ],
      "has_bonus": "-",
      "opp_has_bonus": "-",
      "action_condition": "Para rolagens não necessariamente contra um NPC ou outro Jogador",
      "action_formula_lit": "-",
      "action_formula_array": "-",
      "action_energy": "-",
      "resultminus3": "Ver resultados do outro lado;",
      "resultminus2": "Ver resultados do outro lado;",
      "resultminus1": "Ver resultados do outro lado;",
      "result0": "Ver resultados do outro lado;",
      "result1": "Ver resultados do outro lado;",
      "result2": "Ver resultados do outro lado;",
      "result3": "Ver resultados do outro lado;",
      "action_group_possib": "-",
      "action_detail": "-"
    }
  }
]
};
